### PR TITLE
allow video link to support youtube videos

### PR DESCRIPTION
**Pull request by xumaple**

### CODE REVIEW

**Comment by thedomcab** [comment]
did you see the vimeo javascript being loaded?

**Comment by xumaple** [comment]
> did you see the vimeo javascript being loaded?

not sure what you mean?

**Comment by thedomcab** [comment]
https://github.com/hmcc-global/hmccaa-web/pull/433/files#diff-5a08f1da09b9b6ba9851cdb29ee46ef8aadb30df1acd4bcf8c3709f15764c62fL122

this line number what i meant.

**Review by thedomcab — APPROVED** [review]

**Comment by xumaple** [comment]
History got messed up. Trying in a new PR [here](#455)

**Pull request closed without merging**
