### PR TITLE
[88] Fix padding in footer for mobile view

### PR DESCRIPTION
**Pull request by jchenggggg**
Fixes https://github.com/hmcc-global/hmccaa-web/issues/102

Before:
Screenshot 2023-12-22 at 10 55 53 AM

After:
Screenshot 2023-12-22 at 10 55 34 AM

### CODE REVIEW

**Comment by thedomcab** [comment]
What does desktop look like with your changes?

**Comment by jchenggggg** [comment]
@thedomcab 
Screenshot 2023-12-27 at 1 12 31 PM

**Comment by thedomcab** [comment]
Ain't the columns for the text links in the middle are too off from the mock?
image

if you are fine with it, then i can approve it.

**Comment by jchenggggg** [comment]
> Ain't the columns for the text links in the middle are too off from the mock? image
> 
> if you are fine with it, then i can approve it.

@thedomcab Yes, but they were like that before... This task was just for the mobile view so I just focused on that. I think the only change I made for the desktop view was to remove the extra line and align the copyright thing

Here's what the desktop view looked like before
Screenshot 2023-12-28 at 10 22 29 AM

**Review by thedomcab — APPROVED** [review]

**Pull request merged**
