### PR TITLE
[74] fix links

### LINKED ISSUE #86: Fix links in various pages

### PR DESCRIPTION
**Pull request by Brandt-Bowling**
Add missing links throughout 
fixes #86

### CODE REVIEW

**Comment by thedomcab** [comment]
I did some reach on links, based on this page: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/
Gatsby recommends to use Link component only for this specific gatsby site.  and any external links we should use normal anchor tag (a). the links works still. what are your thoughts?

**Comment by Brandt-Bowling** [comment]
> I did some reach on links, based on this page: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/
> Gatsby recommends to use Link component only for this specific gatsby site.  and any external links we should use normal anchor tag (a). the links works still. what are your thoughts?

I saw that as well but our primary/secondary button link component uses the Gatsby Link. Should we refactor the button links to either use a Link or anchor tag?

**Comment by thedomcab** [comment]
That is the reason I bring this up.  For now, we can accept the changes and not worry about or we can refactor the code.  It is up to you.  I just want to bring it up if you do not know. 


@xumaple  do you any input on what gatsby recommends to do for links? here is the documentation on it: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/

**Comment by xumaple** [comment]
> @xumaple do you any input on what gatsby recommends to do for links? here is the documentation on it: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/

Also agree that it doesn't have to be this PR, but I would refactor it as follows at some point:

Change everything to use our own `Link` function, which takes both `href` and `to` parameters - if `href` is given, assumes it's to a non-Gatsby page and links with `<a>`, but if `to` is given, then uses `<Gatsby::Link>` component. (of course, could add the other optional params for each of those in there as well)

**Comment by Brandt-Bowling** [comment]
Okay, maybe just add it as another card for later and call it good for now?

**Review by thedomcab — APPROVED** [review]

**Pull request merged**
