### PR TITLE
feat(about page): Add link to partners page

### PR DESCRIPTION
**Pull request by jchenggggg**
The HMI page was already created in https://github.com/hmcc-global/hmccaa-web/pull/69 but not linked

### CODE REVIEW

**Review by thedomcab — COMMENTED** [review]
What happen to the partners.js file?

**Comment by jchenggggg** [comment]
> What happen to the partners.js file?

`partners.js` only contained scaffolding for what was already implemented in `hmi.js`

**Review by thedomcab — APPROVED** [review]
okay. i just wonder how partners.js was still in main branch for this long when hmi.js replaces it. Thanks for the update.

**Comment by xumaple** [comment]
Can we move `hmi.js` to `partners.js`? I think `/about/partners` is the name that the original design called for.

**Review by xumaple — CHANGES_REQUESTED** [review]
rename hmi to partners

**Comment by jchenggggg** [comment]
> rename hmi to partners

@xumaple for what it's worth, in the design the breadcrumbs say "HMI". Do we still want to rename the page to "Partners"?

Screenshot 2023-12-27 at 1 10 08 PM

**Comment by xumaple** [comment]
> > rename hmi to partners
> 
> 
> 
> @xumaple for what it's worth, in the design the breadcrumbs say "HMI". Do we still want to rename the page to "Partners"?
> 
> 
> 
> Screenshot 2023-12-27 at 1 10 08 PM
> 
> 

Phil confirmed that about/hmi is better. My apologies. I have no other concerns

**Review by xumaple — APPROVED** [review]

**Comment by xumaple** [comment]
I think you need to rebase though

**Pull request merged**
